version = 0.1
[default.deploy.parameters]
stack_name = "sam-lambda-32"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
resolve_s3 = true