version = 0.1
[default.deploy.parameters]
stack_name = "sam-lambda-32"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
s3_bucket = "pgr301-couch-explorers"