name: Docker Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          version="1.0.3"
          rev=$(git rev-parse --short HEAD)
          dynamic_tag="${version}-${rev}"
          echo "Dynamic tag is: $dynamic_tag"

          image_latest="${DOCKER_USERNAME}/sqs_client_32:latest"
          image_dynamic="${DOCKER_USERNAME}/sqs_client_32:${dynamic_tag}"
          echo "Latest image reference: $image_latest"
          echo "Dynamic image reference: $image_dynamic"
          
          echo "Building and tagging Docker images..."
          docker build ./java_sqs_client \
            -t "$image_latest" \
            -t "$image_dynamic"

          echo "Pushing Docker images..."
          docker push "$image_latest"
          docker push "$image_dynamic"